### ISSUE TITLE
Corrupt PNG files in Connected Paths V1.1

### ISSUE THREAD

**Issue by fernpaws** [Jacosvaldo/Connected-Paths#1]
Issue: When using Connected Paths V1.1 (obtained from https://modrinth.com/resourcepack/connected-paths/version/1.1), some textures do now show proper connections (see image).

![image](https://github.com/Jacosvaldo/Connected-Paths/assets/54524320/3dd09dfd-a7c2-49e2-ba7c-f976fc6a5129)

Apparent fix: Some PNG files seem to actually be .PSD files renamed, see (4.png, 5.png, 6.png, 10.png, 11.png, 12.png, 13.png & 16.png) in `assets\minecraft\optifine\ctm\_overlay\gravel` for some examples.

![image](https://github.com/Jacosvaldo/Connected-Paths/assets/54524320/ee9384b4-e582-4e9d-87c5-5a6da6f6277d)

Opening these in photoshop and re-exporting them as PNGs fixes the issue.

There could be more than just the gravel textures with this issue, I haven't checked them all.

**Comment by Jacosvaldo** [comment]
At first I was saving the textures manually so I probably saved some with the wrong file type, probably until the end of the day I'll fix that.
Thank you very much for the report
